from typing import Any, final
from .models import (
    ComposeSpecification,
    Config,
    Include,
    Model,
    Network,
    Secret,
    Service,
    Volume,
)

@final
class PyCompose:
    def __contains__(self, /, name: str) -> bool: ...
    def __eq__(self, /, other: PyCompose) -> bool: ...
    def __len__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...
    @property
    def configs(self, /) -> dict[str, Config] | None: ...
    @configs.setter
    def configs(self, /, value: dict[str, Config] | None) -> None: ...
    @property
    def extensions(self, /) -> dict[str, Any]: ...
    @extensions.setter
    def extensions(self, /, value: dict[str, Any]) -> None: ...
    @staticmethod
    def from_dict(dict: ComposeSpecification) -> PyCompose: ...
    @staticmethod
    def from_json(json: str) -> PyCompose: ...
    @staticmethod
    def from_yaml(yaml: str) -> PyCompose: ...
    def get_service(self, /, name: str) -> Service | None: ...
    @property
    def include(self, /) -> list[Include] | None: ...
    @include.setter
    def include(self, /, value: list[Include] | None) -> None: ...
    @property
    def name(self, /) -> str | None: ...
    @name.setter
    def name(self, /, value: str | None) -> None: ...
    @property
    def networks(self, /) -> dict[str, Network | None] | None: ...
    @networks.setter
    def networks(self, /, value: dict[str, Network | None] | None) -> None: ...
    def remove_service(self, /, name: str) -> Service | None: ...
    @property
    def secrets(self, /) -> dict[str, Secret] | None: ...
    @secrets.setter
    def secrets(self, /, value: dict[str, Secret] | None) -> None: ...
    def service_names(self, /) -> list[str]: ...
    @property
    def services(self, /) -> dict[str, Service] | None: ...
    @services.setter
    def services(self, /, value: dict[str, Service] | None) -> None: ...
    def set_service(self, /, name: str, service: Service) -> None: ...
    def to_spec(self, /) -> ComposeSpecification: ...
    def to_dict(self, /) -> dict[str, Any]: ...
    def to_json(self, /) -> str: ...
    def to_yaml(self, /) -> str: ...
    def validate(self, /) -> None: ...
    def validate_configs(self, /) -> None: ...
    def validate_networks(self, /) -> None: ...
    def validate_secrets(self, /) -> None: ...
    def validate_volumes(self, /) -> None: ...
    @property
    def version(self, /) -> str | None: ...
    @version.setter
    def version(self, /, value: str | None) -> None: ...
    @property
    def volumes(self, /) -> dict[str, Volume | None] | None: ...
    @volumes.setter
    def volumes(self, /, value: dict[str, Volume | None] | None) -> None: ...

@final
class PyOptions:
    def __init__(self, /, apply_merge: bool = False) -> None: ...
    @property
    def apply_merge(self, /) -> bool: ...
    @apply_merge.setter
    def apply_merge(self, /, val: bool) -> None: ...
    def from_yaml(self, /, yaml: str) -> PyCompose: ...

def format_duration(secs: float) -> str: ...
def parse_duration(s: str) -> float: ...
