from typing import Any, final

@final
class PyCompose:
    def __contains__(self, /, name: str) -> bool: ...
    def __eq__(self, /, other: PyCompose) -> bool: ...
    def __len__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...
    @property
    def configs(self, /) -> Any: ...
    @configs.setter
    def configs(self, /, value: Any) -> None: ...
    @property
    def extensions(self, /) -> Any: ...
    @extensions.setter
    def extensions(self, /, value: Any) -> None: ...
    @staticmethod
    def from_dict(dict: dict) -> PyCompose: ...
    @staticmethod
    def from_json(json: str) -> PyCompose: ...
    @staticmethod
    def from_yaml(yaml: str) -> PyCompose: ...
    def get_service(self, /, name: str) -> Any: ...
    @property
    def include(self, /) -> Any: ...
    @include.setter
    def include(self, /, value: Any) -> None: ...
    @property
    def name(self, /) -> Any: ...
    @name.setter
    def name(self, /, value: Any) -> None: ...
    @property
    def networks(self, /) -> Any: ...
    @networks.setter
    def networks(self, /, value: Any) -> None: ...
    def remove_service(self, /, name: str) -> Any: ...
    @property
    def secrets(self, /) -> Any: ...
    @secrets.setter
    def secrets(self, /, value: Any) -> None: ...
    def service_names(self, /) -> list[str]: ...
    @property
    def services(self, /) -> Any: ...
    @services.setter
    def services(self, /, value: Any) -> None: ...
    def set_service(self, /, name: str, service: Any) -> None: ...
    def to_dict(self, /) -> Any: ...
    def to_json(self, /) -> str: ...
    def to_yaml(self, /) -> str: ...
    def validate(self, /) -> None: ...
    def validate_configs(self, /) -> None: ...
    def validate_networks(self, /) -> None: ...
    def validate_secrets(self, /) -> None: ...
    def validate_volumes(self, /) -> None: ...
    @property
    def version(self, /) -> Any: ...
    @version.setter
    def version(self, /, value: Any) -> None: ...
    @property
    def volumes(self, /) -> Any: ...
    @volumes.setter
    def volumes(self, /, value: Any) -> None: ...

@final
class PyOptions:
    def __new__(cls, /, apply_merge: bool = False) -> PyOptions: ...
    @property
    def apply_merge(self, /) -> bool: ...
    @apply_merge.setter
    def apply_merge(self, /, val: bool) -> None: ...
    def from_yaml(self, /, yaml: str) -> PyCompose: ...

def format_duration(secs: float) -> str: ...
def parse_duration(s: str) -> float: ...
